project:
  type: website
  output-dir: docs

website:
  title: "Proyecto IES"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
        
      - href: areas.qmd
        text: "Areas"
        menu: 
          - href: area_1.qmd
            text: "Área 1"
            
          - href: area_2.qmd
            text: "Área 2"
        
      - href: bibliografia.qmd
        text: "Bibliografiaa"
        
      - href: mas_informacion.qmd
        text: "Mas informacion"
        
      - icon: github
        href: https://github.com/angellds3
      - icon: linkedin
        href: https://www.linkedin.com/in/angel-llanos-b3185a232/

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

