project:
  type: website
  output-dir: docs

website:
  title: "IEST: Consultoria estadística"
  favicon: "images/logo.png"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
            
        
      - text: "Nuestras herramientas"
        href: herramientas.qmd
        
        
      - text: "Proyectos"
        href: proyectos.qmd
        
        
      - text: "Contacto"
        href: contacto.qmd
        
        
      - icon: github
        href: https://github.com/angellds3
      - icon: linkedin
        href: https://www.linkedin.com/in/angel-llanos-b3185a232/

format:
  html:
    theme: lux
    # or morph
    css: styles.css
    toc: true

editor: visual

