project:
  type: website
  output-dir: docs

website:
  title: "Sitio web Quarto: tutorial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: github
        href: https://github.com/angellds3
      - icon: linkedin
        href: https://www.linkedin.com/in/angel-llanos-b3185a232/

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

